name: Docker Image CI

on:
  push:
    branches: [ "branch-cd-1" ]
  pull_request:
    branches: [ "branch-cd-1" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{secrets.GOOGLE_PROJECT}}
        service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        export_default_credentials: true
        # List of Cloud SDK components to install
        # install_components: # optional
    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/proyecto-2/micro-web:0.0.1 .
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/proyecto-2/micro-web:0.0.1
